name: Ruby Unit Testing
inputs:
  ruby-version:
    required: true
    type: string
    default: default
  bundler-env:
    required: false
    type: string
    default: development
  setup-db:
    description: "Whether or not to setup database with rake db commands"
    required: false
    type: string
    default: "true"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: rentpath/actions-services-ruby-deps@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-env: ${{ inputs.bundler-env }}
    - name: Setup DB
      if: ${{ inputs.setup-db == "true" }}
      run: |
        bundle exec rake db:reset db:seed
    - name: Unit test
      run: |
        bundle exec rspec
      shell: bash
      env:
        RACK_ENV: ${{ inputs.bundler-env }}
        RAILS_ENV: ${{ inputs.bundler-env }}
        APPLICATION_ENVIRONMENT: ${{ inputs.bundler-env }}
