name: Ruby Unit Testing
inputs:
  ruby-version:
    required: false
    type: string
    default: default
  bundler-env:
    required: false
    type: string
    default: development
  seed-db:
    description: "Specify whether to seed db, optional"
    required: false
    type: string
  # using a string because booleans currently converted to strings
  # within workflow dispatches and composite actions
  # https://github.com/actions/runner/issues/1483
  skip-checkout:
    required: false
    default: 'false'
    type: string
  update-db:
    required: false
    default: 'true'
    type: string
runs:
  using: composite
  steps:
    - name: Optionally check out code
      if: inputs.skip-checkout == 'false'
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: mmaiza/actions-services-ruby-deps@main
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-env: ${{ inputs.bundler-env }}
    - name: Seeding
      if: ${{ inputs.seed-db }}
      run: |
        bundle exec rake db:seed
      env:
        RACK_ENV: ${{ inputs.bundler-env }}
        RAILS_ENV: ${{ inputs.bundler-env }}
        APPLICATION_ENVIRONMENT: ${{ inputs.bundler-env }}
      shell: bash
    - name: Update db
      if: inputs.update-db == 'true'
      run: |
        bundle exec rake db:reset db:seed
      shell: bash
      env:
        RACK_ENV: ${{ inputs.bundler-env }}
        RAILS_ENV: ${{ inputs.bundler-env }}
        APPLICATION_ENVIRONMENT: ${{ inputs.bundler-env }}
    - name: Unit test
      run: |
        bundle exec rspec
      shell: bash
      env:
        RACK_ENV: ${{ inputs.bundler-env }}
        RAILS_ENV: ${{ inputs.bundler-env }}
        APPLICATION_ENVIRONMENT: ${{ inputs.bundler-env }}
